- id: rentadora_rentant
  alias: Rentadora - Rentant
  trigger:
  - above: '60'
    entity_id: sensor.sala_maquines_endoll_rentadora_consum_actual
    for: 00:00:10
    platform: numeric_state
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: input_select.sala_maquines_estat_rentadora
      state: Rentant
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.sala_maquines_estat_rentadora
      option: Rentant
    entity_id: input_select.sala_maquines_estat_rentadora
  mode: single
- id: rentadora_stand_by
  alias: Rentadora - Stand-by
  trigger:
  - below: '5'
    entity_id: sensor.sala_maquines_endoll_rentadora_consum_actual
    for: 00:01:00
    platform: numeric_state
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.sala_maquines_estat_rentadora
      option: Stand-by
    entity_id: input_select.sala_maquines_estat_rentadora
  mode: single
- id: rentadora_llesta
  alias: Rentadora ha acabat
  trigger:
  - entity_id: input_select.sala_maquines_estat_rentadora
    from: Rentant
    platform: state
    to: Stand-by
  action:
  - type: turn_off
    device_id: 552a2c8dfcee11ea91ae19105657d7e9
    entity_id: switch.sala_maquines_endoll_rentadora
    domain: switch
  - data:
      option: Apagada
    entity_id: input_select.sala_maquines_estat_rentadora
    service: input_select.select_option
  mode: single
- id: '1600462979682'
  alias: Rentadora apagada manual
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 552a2c8dfcee11ea91ae19105657d7e9
    entity_id: switch.sala_maquines_endoll_rentadora
    domain: switch
  condition: []
  action:
  - data:
      option: Apagada
    entity_id: input_select.sala_maquines_estat_rentadora
    service: input_select.select_option
  mode: single
- id: '1601400826100'
  alias: Encendre llum TV a les 21:00 si la TV està encesa
  description: Encendre llum TV a les 21:00 si la TV està encesa
  trigger:
  - platform: time_pattern
    hours: '21'
    minutes: '00'
  condition:
  - condition: device
    device_id: de01dbffc14946daa8d83857ae5d8229
    domain: media_player
    entity_id: media_player.menjador_tv
    type: is_on
  - condition: state
    entity_id: light.menjador_llum_tv
    state: 'off'
  action:
  - type: turn_on
    device_id: 9b7ecb30fd1a11ea901e1148b48278d9
    entity_id: light.menjador_llum_tv
    domain: light
  mode: single
- id: '1601400826101'
  alias: Encendre llum TV a partir de les 21:00 quan s'encengui la TV
  description: Encendre llum TV a les 21:00 quan s'encengui la TV
  trigger:
  - platform: state
    entity_id: media_player.menjador_tv
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '21:00'
  - condition: state
    entity_id: light.menjador_llum_tv
    state: 'off'
  action:
  - type: turn_on
    device_id: 9b7ecb30fd1a11ea901e1148b48278d9
    entity_id: light.menjador_llum_tv
    domain: light
  mode: single
- id: '1601402521291'
  alias: Apaga llum TV si ja fa 2 minuts que s’ha apagat la TV
  description: Apaga la llum TV si ja fa 2 minuts que s'ha apagat la TV
  trigger:
  - platform: state
    entity_id: media_player.menjador_tv
    from: 'on'
    to: 'off'
    for:
      minutes: 2
  condition:
  - condition: state
    entity_id: light.menjador_llum_tv
    state: 'on'
  - condition: state
    entity_id: media_player.menjador_tv
    state: 'off'
  action:
  - type: turn_off
    device_id: 9b7ecb30fd1a11ea901e1148b48278d9
    entity_id: light.menjador_llum_tv
    domain: light
  mode: single
- id: 'apaga_endoll_tv_quan_tv_apagada'
  alias: Apaga Endoll TV si ja fa 2 minuts que s’ha apagat la TV
  description: Apaga la llum TV si ja fa 2 minuts que s'ha apagat la TV
  trigger:
  - platform: state
    entity_id: media_player.menjador_tv
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.regleta_menjador_darrera_tv_mss425f_switch_2
    state: 'on'
  action:
  - type: turn_off
    device_id: 5c127e650dfb11eb81db657c437003bb
    entity_id: switch.regleta_menjador_darrera_tv_mss425f_switch_2
    domain: switch
  mode: single

- id: 'enviar_registre_temperatures_i_hores_a_google_spreadsheets_via_IFTTT'
  alias: Enviar el registre de temperatures i l'hora a la que s'han produït a un full de Google Spreadsheet via IFTTT
  trigger:
    platform: state
    entity_id: !secret internet_router_entity_id
    to: 'home'
  action:
    - delay: 
        minutes: 5
    - service: ifttt.trigger
      data:
        event: "registre_temperatura_exterior"
        value1: "Temperatura Mínima {{ (as_timestamp(now()) - (24*3600)) | timestamp_custom('%d/%m/%Y', True) }}"
        value2: "{{ states.sensor.yesterday_min_temperature.attributes.temperature }}"
        value3: "{{ states.sensor.yesterday_min_temperature.attributes.time }}"
    - service: ifttt.trigger
      data:
        event: "registre_temperatura_exterior"
        value1: "Temperatura Màxima {{ (as_timestamp(now()) - (24*3600)) | timestamp_custom('%d/%m/%Y', True) }}"
        value2: "{{ states.sensor.yesterday_max_temperature.attributes.temperature }}"
        value3: "{{ states.sensor.yesterday_max_temperature.attributes.time }}" 