- id: rentadora_rentant
  alias: Rentadora - Rentant
  trigger:
  - above: '60'
    entity_id: sensor.sala_maquines_endoll_rentadora_consum_actual
    for: 00:00:10
    platform: numeric_state
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: input_select.sala_maquines_estat_rentadora
      state: Rentant
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.sala_maquines_estat_rentadora
      option: Rentant
    entity_id: input_select.sala_maquines_estat_rentadora
  mode: single
- id: rentadora_stand_by
  alias: Rentadora - Stand-by
  trigger:
  - below: '5'
    entity_id: sensor.sala_maquines_endoll_rentadora_consum_actual
    for: 00:01:00
    platform: numeric_state
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.sala_maquines_estat_rentadora
      option: Stand-by
    entity_id: input_select.sala_maquines_estat_rentadora
  mode: single
- id: rentadora_llesta
  alias: Rentadora ha acabat
  trigger:
  - entity_id: input_select.sala_maquines_estat_rentadora
    from: Rentant
    platform: state
    to: Stand-by
  action:
  - type: turn_off
    device_id: 552a2c8dfcee11ea91ae19105657d7e9
    entity_id: switch.sala_maquines_endoll_rentadora
    domain: switch
  - data:
      option: Apagada
    entity_id: input_select.sala_maquines_estat_rentadora
    service: input_select.select_option
  mode: single
- id: '1600462979682'
  alias: Rentadora apagada manual
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 552a2c8dfcee11ea91ae19105657d7e9
    entity_id: switch.sala_maquines_endoll_rentadora
    domain: switch
  condition: []
  action:
  - data:
      option: Apagada
    entity_id: input_select.sala_maquines_estat_rentadora
    service: input_select.select_option
  mode: single
- id: '1601400826100'
  alias: Encendre llum TV a les 21:00 si la TV està encesa
  description: Encendre llum TV a les 21:00 si la TV està encesa i la làmpara de peu no està encesa
  trigger:
  - platform: time_pattern
    hours: '21'
    minutes: '00'
  condition:
  - condition: device
    device_id: de01dbffc14946daa8d83857ae5d8229
    domain: media_player
    entity_id: media_player.menjador_tv
    type: is_on
  - condition: state
    entity_id: switch.menjador_endoll_lampara_de_peu
    state: 'off'
  - condition: state
    entity_id: light.menjador_llum_tv
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - type: turn_on
    device_id: 9b7ecb30fd1a11ea901e1148b48278d9
    entity_id: light.menjador_llum_tv
    domain: light
  mode: single
- id: '1601400826101'
  alias: Encendre llum TV a partir de les 21:00 quan s'encengui la TV
  description: Encendre llum TV a les 21:00 quan s'encengui la TV si la làmpara de peu no està encesa
  trigger:
  - platform: state
    entity_id: media_player.menjador_tv
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: '21:00'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: switch.menjador_endoll_lampara_de_peu
    state: 'off'
  - condition: state
    entity_id: light.menjador_llum_tv
    state: 'off'
  action:
  - type: turn_on
    device_id: 9b7ecb30fd1a11ea901e1148b48278d9
    entity_id: light.menjador_llum_tv
    domain: light
  mode: single
- id: '1601402521291'
  alias: Apaga llum TV si ja fa 2 minuts que s’ha apagat la TV
  description: Apaga la llum TV si ja fa 2 minuts que s'ha apagat la TV
  trigger:
  - platform: state
    entity_id: media_player.menjador_tv
    from: 'on'
    to: 'off'
    for:
      minutes: 2
  condition:
  - condition: state
    entity_id: light.menjador_llum_tv
    state: 'on'
  - condition: state
    entity_id: media_player.menjador_tv
    state: 'off'
  action:
  - type: turn_off
    device_id: 9b7ecb30fd1a11ea901e1148b48278d9
    entity_id: light.menjador_llum_tv
    domain: light
  mode: single
- id: 'apaga_endoll_tv_quan_tv_apagada'
  alias: Apaga Endoll TV al apagar la TV
  description: Apaga Endoll al apagar la TV
  trigger:
  - platform: state
    entity_id: media_player.menjador_tv
    from: 'on'
    to: 'off'
  action:
  - type: turn_off
    device_id: 5c127e650dfb11eb81db657c437003bb
    entity_id: switch.regleta_menjador_darrera_tv_mss425f_switch_2
    domain: switch
  mode: single

- id: 'enviar_registre_temperatures_i_hores_a_google_spreadsheets_via_IFTTT'
  alias: Enviar el registre de temperatures i l'hora a la que s'han produït a un full de Google Spreadsheet via IFTTT
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - delay:
        minutes: 5
    - service: ifttt.trigger
      data:
        event: "registre_temperatura_exterior"
        value1: "Temperatura Mínima {{ (as_timestamp(now()) - (24*3600)) | timestamp_custom('%d/%m/%Y', True) }}"
        value2: "{{ states.sensor.yesterday_min_temperature.attributes.temperature }}"
        value3: "{{ states.sensor.yesterday_min_temperature.attributes.time }}"
    - service: ifttt.trigger
      data:
        event: "registre_temperatura_exterior"
        value1: "Temperatura Màxima {{ (as_timestamp(now()) - (24*3600)) | timestamp_custom('%d/%m/%Y', True) }}"
        value2: "{{ states.sensor.yesterday_max_temperature.attributes.temperature }}"
        value3: "{{ states.sensor.yesterday_max_temperature.attributes.time }}"

- id: 'encendre_llum_tv_al_apagar_llum_de_peu_si_tv_encesa'
  alias: Encendre llum TV al apagar la llum de peu si la TV està encesa
  trigger:
    platform: state
    entity_id: switch.menjador_endoll_lampara_de_peu
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: light.menjador_llum_tv
    state: 'off'
  - condition: state
    entity_id: media_player.menjador_tv
    state: 'on'
  action:
  - type: turn_on
    device_id: 9b7ecb30fd1a11ea901e1148b48278d9
    entity_id: light.menjador_llum_tv
    domain: light
  mode: single

- id: 'encendre_llum_de_peu_al_apagar_llum_tv_si_tv_encesa'
  alias: Encendre llum de peu al apagar la llum TV si la TV està encesa
  trigger:
    platform: state
    entity_id: light.menjador_llum_tv
    to: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: switch.menjador_endoll_lampara_de_peu
    state: 'off'
  - condition: state
    entity_id: media_player.menjador_tv
    state: 'on'
  action:
  - data:
      entity_id: switch.menjador_endoll_lampara_de_peu
    service: switch.turn_on
  mode: single

- id: 'timelapse_camera_exterior'
  alias: Agafar captura de la webcam exterior
  trigger:
    - platform: time_pattern
      minutes: /6
  condition:
    - condition: sun
      before: sunset
      before_offset: '01:00:00'
      after: sunrise
      after_offset: '-01:00:00'
  action:
    - service: camera.snapshot
      data:
        filename: >-
                  /config/www/images/webcam/webcam_exterior_{{ now().strftime("%Y%m%d-%H%M") }}.jpg
      entity_id: camera.camara_exterior_mainstream
  mode: single

- id: 'generar_timelapse_camera_exterior'
  alias: 'Generate timelapse '
  description: 'Generar timelapse amb les imatges del dia de la camera exterior'
  trigger:
    - platform: time
      at: '01:30:00'
  condition: []
  action:
    - service: shell_command.delete_empty_files_webcam_exterior
      data: {}
    - service: shell_command.timelapse_webcam_exterior
      data: {}
    - delay: '00:30:00'
    - service: shell_command.delete_files_webcam_exterior
      data: {}
  mode: single

- id: 'apagar endoll esterilla als 95 minuts'
  alias: "Apagar l'endoll de la esterilla si ja s'ha acabat el temps de 90 minuts per al que està programat"
  trigger:
    platform: state
    entity_id: switch.habitacio_matrimoni_inma_endoll_esterilla
    from: 'off'
    to: 'on'
    for:
      hours: 1
      minutes: 35
      seconds: 0
  action:
    service: switch.turn_off
    data:
      entity_id: switch.habitacio_matrimoni_inma_endoll_esterilla

- id: 'encendre router internet a les 7:00 del mati'
  alias: "Encendre l'endoll del router a les 7:00 del matí"
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.despatx_regleta_1_endoll_router_wifi

- id: 'encendre endoll cuina per a carregar mòbils a les 0:00h'
  alias: "Encendre l'endoll de la cuina per carregar els mòbils a partir de les 0:00"
  trigger:
    platform: time
    at: '00:00:00'
  condition:
  alias: "Hi hagi algú a casa"
  condition:
    - condition: state
      entity_id: "group.habitants"
      state: "home"
  action:
    - service: switch.turn_on
      entity_id: switch.cuina_endoll_sintonitzador_tv

- id: 'apagar endoll cuina per a carregar mòbils a les 8:00h'
  alias: "Apagar l'endoll de la cuina per carregar els mòbils a partir de les 8:00"
  trigger:
    platform: time
    at: '07:59:59'
  condition:
  alias: "Hi hagi algú a casa"
  condition:
    - condition: state
      entity_id: "group.habitants"
      state: "home"
  action:
    - service: switch.turn_off
      entity_id: switch.cuina_endoll_sintonitzador_tv

- id: "encendre el ventilador de l'habitació de l'Arlet a les 22h si el ventilador està posat"
  alias: "Encendre el ventilador de l'habitació de l'Arlet a les 22h si el ventilador està posat"
  trigger:
    platform: time
    at: '22:00:59'
  condition:
  - condition: state
    entity_id: "group.habitants"
    state: "home"
  - condition: state
    entity_id: input_boolean.habitacio_arlet_ventilador
    state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.endoll_polivalent_1_relay2

- id: "encendre l'aparell dels mosquits de l'habitació de l'Arlet a les 22h si l'aparell està posat"
  alias: "Encendre l'aparell dels mosquits de l'habitació de l'Arlet a les 22h si l'aparell està posat"
  trigger:
    platform: time
    at: '22:00:59'
  condition:
  - condition: state
    entity_id: "group.habitants"
    state: "home"
  - condition: state
    entity_id: input_boolean.habitacio_arlet_aparell_mosquits
    state: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.endoll_polivalent_1_relay1

- id: "apagar el ventilador de l'habitació de l'Arlet a les 7h 59m si el ventilador està posat"
  alias: "Apagar el ventilador de l'habitació de l'Arlet a les 7h 59m si el ventilador està posat"
  trigger:
    platform: time
    at: '07:59:59'
  condition:
  - condition: state
    entity_id: "group.habitants"
    state: "home"
  - condition: state
    entity_id: input_boolean.habitacio_arlet_ventilador
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.endoll_polivalent_1_relay2

- id: "apagar l'aparell dels mosquits de l'habitació de l'Arlet a 7h 59m si l'aparell està posat"
  alias: "apagar l'aparell dels mosquits de l'habitació de l'Arlet a les 7h 59m si l'aparell està posat"
  trigger:
    platform: time
    at: '07:59:59'
  condition:
  - condition: state
    entity_id: "group.habitants"
    state: "home"
  - condition: state
    entity_id: input_boolean.habitacio_arlet_aparell_mosquits
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.endoll_polivalent_1_relay1