
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  external_url: !secret homeassistant_external_url
  internal_url: !secret homeassistant_internal_url
  packages: !include_dir_named integrations
  customize: !include customize.yaml

media_player:

browser_mod:

binary_sensor:
  - platform: workday
    country: ES

shell_command: !include shell_command/shell_commands.yaml

input_boolean: !include_dir_named input_boolean/
input_text: !include_dir_named input_text/
input_select: !include_dir_named input_select/
sensor: !include_dir_list sensors/
