
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  external_url: !secret homeassistant_external_url
  internal_url: !secret homeassistant_internal_url
  packages: !include_dir_named integrations
  customize: !include customize.yaml
