
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  external_url: !secret homeassistant_external_url
  internal_url: !secret homeassistant_internal_url
  packages: !include_dir_named integrations

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

wake_on_lan:

webostv:
  host: !secret lg_tv_menjador_ip
  name: TV LG Menjador
  turn_on_action:
    - service: switch.turn_on
      data:
        entity_id: switch.regleta_menjador_darrera_tv_mss425f_switch_2
    - delay:
        seconds: 30
    - service: wake_on_lan.send_magic_packet
      data:
        "mac": !secret lg_tv_menjador_mac
  customize:
    sources:
      - livetv
      - youtube
      - primevideo

media_player:

input_select:
  sala_maquines_estat_rentadora:
    name: Estat rentadora
    options:
      - Apagada
      - Stand-by
      - Rentant
    initial: Apagada
    icon: mdi:washing-machine

home_connect:
  client_id: !secret home_connect_client_id
  client_secret: !secret home_connect_client_secret

browser_mod:

ifttt:
  key: !secret ifttt_key

binary_sensor:
  - platform: workday
    country: ES

google_assistant: !include google_assistant.yaml

shell_command: !include shell_command/shell_commands.yaml

recorder:
  purge_keep_days: 10
  db_url: !secret recorder_db_url

telegram_bot:
  platform: polling
  api_key: !secret telegram_bot_api_key
  allowed_chat_ids:
    - !secret telegram_bot_chat_id_eduard
notify:
  - name: telegram_text_message_eduard
    platform: telegram
    chat_id: !secret telegram_bot_chat_id_eduard
  - name: telegram_voice_call_eduard
    platform: rest
    resource: https://api.callmebot.com/start.php
    data:
      source: HA
      user: !secret telegram_voice_call_username_eduard
      lang: ca-es-Standard-A
      rpt: 2

input_boolean: !include_dir_named input_boolean/
input_text: !include_dir_named input_text/
sensor: !include_dir_list sensors/
