substitutions:
  device: shp7_endoll_tauleta_nit_edu
  name: shp7_endoll_tauleta_nit_edu
  static_ip: 192.168.0.32
  gateway: 192.168.0.1
  subnet: 255.255.255.0
  update_interval: 10min
  current_res: '0.002291'
  voltage_div: '940'

esphome:
  name: '${device}'
  platform: ESP8266
  board: esp8285

<<: !include common/common.yaml

binary_sensor:
  - <<: !include common/shp7/binary_sensor_button1.yaml
  - <<: !include common/shp7/binary_sensor_button2.yaml

output:
  - <<: !include common/shp7/output_led1.yaml
  - <<: !include common/shp7/output_led2.yaml

switch:
  - <<: !include common/shp7/switch_relay1.yaml
  - <<: !include common/shp7/switch_relay2.yaml

<<: !include common/shp7/status_led.yaml

sensor:
  - <<: !include common/sensors.yaml
  - <<: !include common/shp7/sensor-hlw8012.yaml
  - <<: !include common/shp7/sensor-daily-energy.yaml
